run:
  skip-dirs-use-default: false

linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
